item {
  id: 1
  name: 'bin'
}

item {
  id: 2
  name: 'bin_cover'
}

item {
  id: 3
  name: 'buoy_green'
}

item {
  id: 4
  name: 'buoy_red'
}

item {
  id: 5
  name: 'buoy_yellow'
}

item {
  id: 6
  name: 'channel'
}

item {
  id: 7
  name: 'object_dropoff'
}

item {
  id: 8
  name: 'object_pickup'
}

item {
  id: 9
  name: 'path_marker'
}

item {
  id: 10
  name: 'qual_gate'
}

item {
  id: 11
  name: 'torpedo_cover'
}

item {
  id: 12
  name: 'torpedo_hole'
}

item {
  id: 13
  name: 'torpedo_target'
}
